[package]
name = "rs_battle_for_nation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
itertools = "0.10.0"
clap = "2.33.3"
log = "0.4"
env_logger = "0.9"
num = "0.4"